# Generated by Django 5.0.2 on 2024-02-23 23:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[accounts.models.validate_phone], verbose_name='User Phone number'),
        ),
    ]
