# Generated by Django 5.0.2 on 2024-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('Male', 'Male'), ('Female', 'Female')], default='male', max_length=6, verbose_name='User gender'),
        ),
    ]
